# Generated by Django 6.1 on 2026-08-27 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True)),
                ('food_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('manual_code', models.CharField(blank=True, max_length=100, null=True)),
                ('mail_sent', models.BooleanField(default=False)),
                ('mail_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
